version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "firstlamdastack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-j85ywnu800iw"
s3_prefix = "firstlamdastack"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "customer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-j85ywnu800iw"
s3_prefix = "customer"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
