version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "customer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-j85ywnu800iw"
s3_prefix = "customer"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
