AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Customer API
Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Runtime: java11
    Environment:
      Variables:
        PARAM1: VALUE
        # JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1

Resources:
  customer:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
  CreateCustomerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: customer
      Handler: com.anhnt.customer.App::createCustomer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref customer
      Events:
        CreateCustomerEvent:
          Type: Api
          Properties:
            Path: /customers
            Method: post

  GetCustomerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: customer
      Handler: com.anhnt.customer.App::getCustomer

      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref customer
      Events:
        GetCustomerEvent:
          Type: Api
          Properties:
            Path: /customers/{id}
            Method: get
